CXX='g++ -std=c++11'
CFLAGS  = -pedantic-errors -Wall
TARGET = practica2make
all: $(TARGET)
 
  $(TARGET): $(TARGET).c
              $(CC) $(CFLAGS) -o $(TARGET) $(TARGET).c
 
  clean:
              $(RM) $(TARGET)