#aqui se poner el estandar, modificar variable c por 
#g++ -std=c++11
#g++ -ansi
#g++ -std=c++98
#g++ -std=c++03
#g++ -std=c++14
#g++ -std=c++17
#g++ -std=c++20
C=g++ -std=c++11
#banderas
CFLAGS = -pedantic-errors -Wall
all:practica2make.cpp
	$(C) $(CFLAGS) -o practica2make practica2make.cpp